# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

enableSqsTerminationDraining: true
enablePrometheusServer: true

image:
  repository: ${aws_htc_ecr}/ecr-public/aws-ec2/aws-node-termination-handler

tolerations:
  - key: "htc/node-type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

rbac:
  pspEnabled: false
