# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

image:
  repository: ${aws_htc_ecr}/ecr-public/aws-observability/aws-for-fluent-bit

env:
  - name : AWS_STS_REGIONAL_ENDPOINTS
    value: regional

cloudWatch:
  enabled: true
  region: ${region}

rbac:
  pspEnabled: false

firehose:
  enabled: false

kinesis:
  enabled: false

elasticsearch:
  enabled: false
