# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

image:
  repository: ${aws_htc_ecr}/ecr-public/cloudwatch-agent/cloudwatch-agent
