# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

grafana.ini:
  auth:
    disable_login_form: true
  auth.anonymous:
    enabled: true

persistence:
  enabled: false

service:
  type: "NodePort"


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80},{\"HTTPS\":443}]"
    alb.ingress.kubernetes.io/certificate-arn: "${alb_certificate_arn}"
    alb.ingress.kubernetes.io/actions.ssl-redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": { \"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
    alb.ingress.kubernetes.io/subnets: "${vpc_public_subnets}"
  path: /*
  pathType: ImplementationSpecific
  hosts:
    - ""
  extraPaths:
    - path: /*
      pathType: ImplementationSpecific
      backend:
        service:
          name: ssl-redirect
          port:
            name: use-annotation


adminPassword: "${grafana_configuration_admin_password}"

nodeSelector:
  htc/node-type: "core"

tolerations:
  - key: "htc/node-type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"


datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: 'POST'
    - name: InfluxDB
      type: influxdb
      url: influxdb.influxdb.svc.cluster.local:8086
      access: proxy
      isDefault: false
      database: measurementsdb
      jsonData:
        httpMode: POST


dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default


dashboards:
  default:
    htc-metrics:
      json: |
        ${htc_metrics_dashboard_json}
    kubernetes-metrics:
      json: |
        ${kubernetes_metrics_dashboard_json}


initChownData:
  image:
    pullPolicy: Always
    repository: "${aws_htc_ecr}/busybox"
    tag: "${grafana_configuration_initChownData_tag}"

image:
  repository: "${aws_htc_ecr}/grafana"
  tag: "${grafana_configuration_grafana_tag}"

downloadDashboardsImage:
  repository: "${aws_htc_ecr}/curl"
  tag: "${grafana_configuration_downloadDashboardsImage_tag}"

sidecar:
  dashboards:
    enabled : true
  image:
    repository: "${aws_htc_ecr}/k8s-sidecar"
    tag: "${grafana_configuration_sidecar_tag}"
