# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

env:
  - name : AWS_STS_REGIONAL_ENDPOINTS
    value: regional

podSecurityContext:
  operator:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

image:
  keda:
    repository: ${aws_htc_ecr}/kedacore/keda
    # Allows people to override tag if they don't want to use the app version
    tag: ${k8s_keda_version}
  metricsApiServer:
    repository: ${aws_htc_ecr}/kedacore/keda-metrics-apiserver
    # Allows people to override tag if they don't want to use the app version
    tag: ${k8s_keda_version}
  webhooks:
    repository: ${aws_htc_ecr}/kedacore/keda-admission-webhooks
    # Allows people to override tag if they don't want to use the app version
    tag: ${k8s_keda_version}
  pullPolicy: Always


nodeSelector:
  htc/node-type: "core"

tolerations:
  - key: "htc/node-type"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"


logging:
  operator:
    ## Logging level for KEDA Operator
    # allowed values: 'debug', 'info', 'error', or an integer value greater than 0, specified as string
    # default value: info
    level: debug
    # allowed values: 'json' or 'console'
    # default value: console
    format: console
    ## Logging time encoding for KEDA Operator
    # allowed values are 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'
    # default value: rfc3339
    timeEncoding: rfc3339
  metricServer:
    ## Logging level for Metrics Server
    # allowed values: '0' for info, '4' for debug, or an integer value greater than 0, specified as string
    # default value: 0
    level: 4

  webhooks:
    ## Logging level for KEDA Operator
    # allowed values: 'debug', 'info', 'error', or an integer value greater than 0, specified as string
    # default value: info
    level: debug
    # allowed values: 'json' or 'console'
    # default value: console
    format: console
    ## Logging time encoding for KEDA Operator
    # allowed values are 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'
    # default value: rfc3339
    timeEncoding: rfc3339
