# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

server:
  retention: 1h

  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s

  image:
    repository: ${aws_htc_ecr}/quay/prometheus/prometheus
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  persistentVolume:
    enabled: false
  tolerations:
    - key: "htc/node-type"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
  nodeSelector:
    htc/node-type: "core"


alertmanager:
  enabled: false


kube-state-metrics:
  enabled: true
  image:
    repository: ${aws_htc_ecr}/kube-state-metrics
    tag: ${kube_state_metrics_tag}
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  tolerations:
    - key: "htc/node-type"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
  nodeSelector:
    htc/node-type: "core"


pushgateway:
  enabled: false


nodeExporter:
  image:
    repository: ${aws_htc_ecr}/quay/prometheus/node-exporter
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  tolerations:
    - key: "htc/node-type"
      operator: "Equal"
      value: "core"
      effect: "NoSchedule"
  nodeSelector:
    htc/node-type: "core"


configmapReload:
  prometheus:
    image:
      repository: ${aws_htc_ecr}/configmap-reload
      tag: ${configmap_reload_tag}
