# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

name: Test-CFN-Nag
on: [push, pull_request]

jobs:
  cfn_nag:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: new_branch
      MAIN_BRANCH: main_branch
      NEW_BRANCH_REPORT_FILE: new_branch_cfn_nag_report_file.sarif
      MAIN_BRANCH_REPORT_FILE: main_branch_cfn_nag_report_file.sarif
      DIFF_REPORTS_FILE: diff_cfn_nag_reports.txt

    steps:
      - name: Checkout the new branch
        uses: actions/checkout@v3
        with: 
          path: ${{ env.NEW_BRANCH }}

      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          repository: awslabs/aws-htc-grid
          path: ${{ env.MAIN_BRANCH }}

      - name: Run cfn_nag on the new branch
        uses: stelligent/cfn_nag@master
        with:
          input_path: ${{ env.NEW_BRANCH }}/deployment/
          extra_args: '-g -o sarif' #-t '..*\/(cfn|cloudformation)\/..*\.yaml' # This flag doesnt seem to be working.
          output_path: ${{ env.NEW_BRANCH_REPORT_FILE }}

      - name: Run cfn_nag on main
        uses: stelligent/cfn_nag@master
        with:
          input_path: ${{ env.MAIN_BRANCH }}/deployment/
          extra_args: '-g -o sarif' #-t '..*\/(cfn|cloudformation)\/..*\.yaml' # This flag doesnt seem to be working.
          output_path: ${{ env.MAIN_BRANCH_REPORT_FILE }}

      - name: Upload cnf_nag scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: "${{ env.NEW_BRANCH_REPORT_FILE }}"

      - name: Save report results for the new branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NEW_BRANCH_REPORT_FILE }}
          path: ${{ env.NEW_BRANCH_REPORT_FILE }}

      - name: Save report results for the main branch
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MAIN_BRANCH_REPORT_FILE }}
          path: ${{ env.MAIN_BRANCH_REPORT_FILE }}

      - name: Generate the diff of reports between main and the new branch
        run: |-
          diff ${{ env.NEW_BRANCH_REPORT_FILE }} ${{ env.MAIN_BRANCH_REPORT_FILE }} >> ${{ env.DIFF_REPORTS_FILE }} || true

      - name: Save diff reports
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIFF_REPORTS_FILE }}
          path: ${{ env.DIFF_REPORTS_FILE }}

      - name: Verify that the number of errors in the new branch does not exceed the number of existing errors in the main branch
        run: |-          
          if [ "$(wc -l < ${{ env.NEW_BRANCH_REPORT_FILE }} )" -gt "$(wc -l < ${{ env.MAIN_BRANCH_REPORT_FILE }} )" ]; then \
            echo "Warning: New branch has more errors!"
            exit 1
          fi
